# Generated by Django 3.2.10 on 2021-12-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='язык'),
        ),
    ]
